% formatting
\documentclass[10pt,a4paper,final]{article}
\usepackage{amssymb,latexsym}
\usepackage{graphicx}
\usepackage{authblk}
\usepackage[margin=0.75in]{geometry}
\usepackage{parskip}
\setlength{\parindent}{0pt}
\usepackage{textgreek}
\usepackage{pbox}
\usepackage{multirow}
\usepackage{changepage}
\usepackage{longtable}
\renewcommand{\thefigure}{M\arabic{figure}}

% command for making a table within the cell of a table
\newcommand{\specialcell}[2][c]{%
  \begin{tabular}[#1]{@{}l@{}}#2\end{tabular}}

% citations
\usepackage[url=false,
            backref=true,
            autocite=superscript,
            hyperref=true,
            style=nature,
            sorting=none,
            maxbibnames=99,
            minbibnames=99, 
            doi=false,url=false,isbn=false]{biblatex}
%\addbibresource{Manual.bib}
\AtEveryBibitem{\clearfield{issn}}
\AtEveryCitekey{\clearfield{issn}}
\DefineBibliographyStrings{english}{%
                                    backrefpage  = {see p.}, % for single page number
                                    backrefpages = {see pp.} % for multiple page numbers
}


% links
\usepackage{color}
\usepackage[usenames,dvipsnames,svgnames,table]{xcolor}
\usepackage[colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=blue]{hyperref}


\begin{document}
%\SweaveOpts{concordance=TRUE}

<<set-options, include=FALSE, cache=FALSE>>=
  opts_knit$set(root.dir="../")
  opts_chunk$set(eval=TRUE,dev="png",dpi=400,tidy=FALSE,message=FALSE,cache=TRUE,warning=FALSE,size="small")
@

\title{Supplement}
\author[1]{\fontsize{10}{11}\selectfont Kevin~M. D'Auria}
             \author[2]{Meghan~J. Bloom}
             \author[2]{Yesenia Reyes}
             \author[2]{Mary~C. Gray}
             \author[2]{Edward~J. van Opstal}
             \author[1]{Jason~A. Papin}
             \author[2]{Erik~L. Hewlett}
             \affil[1]{Department of Biomedical Engineering} 
             \affil[2]{Division of Infectious Diseases and International Health\\
             Department of Medicine}
             \affil[ ]{University of Virginia, Charlottesville, VA}
             \date{}
             \maketitle

\hypersetup{linkcolor=black}
\setcounter{tocdepth}{2}
\tableofcontents
\hypersetup{linkcolor=blue}

% The hidden files and functions that allow this code to run
<<hiddenopts, echo=FALSE, cache=TRUE>>=
source("./R/loadData.R")

small.theme = theme(legend.text = element_text(size=6),
                    legend.key.size = unit(6, "points"),
                    legend.title = element_text(size=6),
                    legend.margin = unit(1, "points"),
                    plot.margin = unit(rep(0,4), "points"),
                    axis.text = element_text(size=6),
                    axis.title = element_text(size=6),
                    strip.text = element_text(size=6),
                    plot.title = element_text(size=8))

ggplot = function(...)
  ggplot2::ggplot(...) + small.theme

qplot = function(...)
  ggplot2::qplot(...) + small.theme

plot.wellList = function(...)
  wellz:::plot.wellList(...) + small.theme
@


\section{Introduction}\label{S:Intro}

This document includes the supplemental data referred to in the manuscript
as well as instructions for how to reproduce our analyses and explore the
data further. Use the clickable table of contents to navigate quickly.
This is a functional document in that scripts (written in the
R programming languange with the \texttt{knitr} package) are embedded, and they were run during
PDF creation to produce the figures and output shown. Thus, the analyses can
be repeated by downloading the source of this document (with the data) or copy-pasting
all of the code into one's own R console.

Most of the functions for processing this data are in the
\texttt{wellz} R package, available at \url{https://github.com/kdauria/wellz}.
All of the supplemental files are wrapped in an R package, called \texttt{imTox},
available at \url{https://github.com/kdauria/imTox}. In this package, the
spreadsheet denoting the compounds and concentrations in each well are in
\texttt{Annotations.csv} and all of the raw data files are in the
\texttt{Data} directory.

<<libraries, tidy=TRUE, echo=TRUE, eval=FALSE>>=
library(wellz)
wells = parse_metadata( metadata="./Annotations2.csv", 
                        data.dir="./Data",
                        parse_fun=wellz:::parse_rtca)
@


\section{ References from manuscript }

\subsection{ Reference 1 }

``The impedance curves of cells treated with TcdA (300 ng/ml) 
and TcdB (10 ng/ml) diverged from controls in 10 and 20 minutes, 
respectively (Supplement).''

<<suppRef1, tidy=TRUE, fig.width=7.5, fig.height=2.5, echo=FALSE>>=
subset = select(wells, file=c("J774-a.txt","J774-b.txt"))
t.subset = normalize_toxin(subset,xlim=c(-2,Inf))
p1 = plot( select(t.subset,"TcdA"), xlim=c(-0.01,0.7), points=TRUE, 
           color="concentration", replicates=TRUE) +
     ylab("Normalize Impedance") + ggtitle("TcdA")
p2 = plot( select(t.subset,"TcdB"), xlim=c(-0.01,1.2), points=TRUE, 
           color="concentration", replicates=TRUE) +
     ylab("Normalize Impedance") + ggtitle("TcdB")
grid.arrange(p1,p2,ncol=2)
@

\subsection{ Reference 2 }

``To confirm the low toxin-sensitivity of neutrophils, we did attempt to 
measure impedance changes of neutrophils in response to toxins, yet 
the variability in these primarily non-adherent cells (impedance 
largely measures adherence) was too high to identify 
differences (Supplement).''

\subsection{ Reference 3 }

``TEXT TO BE ADDED``

\begin{figure}[h!]
  \centering
  \includegraphics[width=\textwidth]{FigS1.jpg}
  \caption[gdTcdB added to HCT8 cells]{
       \textbf{gdTcdB added to HCT8 cells}
  }
  \label{figs1}
\end{figure}


See \ref{S:PMNs}

\section{ Reproducing Figures }\label{S:ReFig}

Below are the scripts to reproduce the figures. The data files
and annotation file needed for the scripts to work are included in
the supplemental data folder. The figures below were exported to PDFs.
Cosmetic alterations (colors, line widths, axes labeling, legends, etc.) were
made with Adobe Illustrator.

\subsection{ Figure 1 }

<<figure1, tidy=TRUE, fig.width=7.5, fig.height=2.5 >>=
subset = select(wells,"TcdA[1000] & !gdTcdB",file="HCT8-4.txt")
t.subset = normalize_toxin( subset, xlim=c(-Inf, 100) )
p1 = plot(t.subset, xlim=c(-43,10), replicates=TRUE, color="concentration" )
p2 = plot(t.subset, xlim=c(-1,10), replicates=TRUE, color="concentration" )
grid.arrange( p1, p2, ncol=2 )
@

\subsection{ Figure 2 }

<< preFigure2, tidy=FALSE, fig.width=7.5, fig.height=4.5, eval=TRUE, results='hide'>>=
# Select the data set used for each cell type
hct8 = select(wells,"HCT8[0-6000]",file="HCT8.txt")
files = list( "CHO.txt", "IMCE.txt", c("HUVEC-a.txt","HUVEC-b.txt"), 
              c("T84-a.txt","T84-b.txt"))
subsets = lapply(files, function(f) select(wells, file = f))
subsets = c(list(hct8), subsets)

# Normalize each subset, slicing different sections of the data (xlims)
# and add smoothers to each subset
xlims = list(c(-1, 43), c(-1, Inf), c(-1, Inf), c(-1, 60), c(-1, 27))
n.subsets = Map(normalize_toxin, subsets, xlim = xlims)
s.subsets = Map(add_smoother, n.subsets, method="composite2",
                w=c(2,1,1,3,3),
                global.change=c(1.5,1,1,1,1),
                max.knots=c(20,10,10,12,12))

######### Panel A. Different cell types. Same concentrations. #########
allwells = do.call("c",s.subsets)
subset = select(allwells, "TcdA[100]", ID="toxinAdd")
p1 = plot(subset, xlim=c(-1,10), replicates=TRUE, sd=FALSE, 
          color="compound", type="total")

######### Panel B. Same cell type. Different toxins ############
subset = select(allwells, "IMCE & (TcdA[100] | TcdB[100])")
p2 = plot(subset, xlim = c(-0.1, 2), replicates=TRUE, sd = FALSE, color="compound")

######## Panel C. MaxS and ABC for IMCE cells ###########
# Calculate ABC for each subset
lower = c( 0,  0,  0,  0,  0)
upper = c(43, 40, 80, 80, 27)
areas = Map( calculate_area, s.subsets, lower, upper, ID="toxinAdd" )
areas.df = rbindlist(areas)

# Calculate MaxS for each subset
xlim = list( c(0.1,30), c(0.1,30), c(0.1,30), c(0.2,30), c(0.2,30))
maxs = Map( calculate_max_rate, s.subsets, ID="toxinAdd", 
            xlim=xlim, direction="negative")
maxs.df = rbindlist(maxs)

#### Make the plots for just IMCE cells
p3a = ggplot( maxs.df[celltype=="IMCE" & compound!="",],
              aes(x=as.numeric(concentration), y=rate, color=compound)) + 
  geom_hline(data=maxs.df[celltype=="IMCE" & compound=="",], 
             aes(intercept=rate), color="blue", linetype="dashed") +
  geom_point() + scale_x_log10()

p3b = ggplot( areas.df[celltype=="IMCE" & compound!="",],
              aes(x=as.numeric(concentration), y=area, color=compound)) + 
  geom_hline(data=areas.df[celltype=="IMCE" & compound=="",], 
             aes(intercept=area), color="blue", linetype="dashed") + 
  geom_point() + scale_x_log10()
p3 = arrangeGrob(p3a, p3b, nrow=2)

####### Panel D. The MCC for each cell type ##############
# The MCC was found by plotting the ABC of each cell type over
# a range of concentrations. The concentration diverging from
# controls was considered the MCC
########## Area beneath curve for all cell types
ggplot(areas.df, aes(x=as.numeric(concentration),y=area,color=compound)) + 
  geom_point() + scale_x_log10() +
  geom_hline( data=areas.df[areas.df$compound==""], 
              aes(yintercept=area,color=compound), linetype="dashed" ) + # controls
  facet_wrap(~celltype, scale="free") +
  xlab("Concentration (ng/ml)")

########## MaxS for all cell types
ggplot(maxs.df, aes(x=as.numeric(concentration),y=rate,color=compound)) + 
  geom_point() + scale_x_log10() +
  geom_hline( data=maxs.df[maxs.df$compound==""], 
              aes(yintercept=rate,color=compound), linetype="dashed" ) + # controls
  facet_wrap(~celltype, scale="free") +
  xlab("Concentration (ng/ml)")
@

After the processing, the four panels can be combined.

<<Figure2, tidy=TRUE, fig.width=7.5, fig.height=4.5>>=
# Manually enter the MCC for each cell type
d = data.frame( type = c( "CHO", "HCT8", "HUVEC", "IMCE", "T84" ),
                a    = c( 1    ,  1    ,  1     ,  0.1  , 0.1   ),
                b    = c( .001 ,  .01  ,  .01  ,  .0001 , 0.1   ) )
p4 = ggplot( d, aes( x=log10(a), y=log10(b), label=type) ) + geom_text() +
  scale_x_reverse(limits=c(0,-4)) + scale_y_reverse(limits=c(0,-4)) + 
  geom_abline(slope=1,intercept=0) + coord_equal() + geom_point(color="red")

# Show the final plot
grid.arrange( p1, p2, p3, p4, ncol=2 )
@

\subsection{ Figure 3 }

<<Figure3top, tidy=FALSE, fig.width=7.5, fig.height=2.5>>=

@

\subsection{ Figure 4 }

<<Figure4, tidy=FALSE, fig.width=7.5, fig.height=5>>=

@

\subsection{ Figure 5 }

<<FigureS1, tidy=FALSE, fig.width=7.5, fig.height=4.5>>=

@

\subsection{ Figure S1 }
<<Figure5, tidy=FALSE, fig.width=7.5, fig.height=2.5>>=

@


\section{ Exploring the data }

All experiments, each involving several experimental conditions, are summarized
in the table below. Independent experiments that occurred on different days are
separated by horizontal lines.
Diagrams of the physical multi-well plates are displayed in \ref{S:plateLayouts}.
The number of cells seeded and all the incubation times can be found in the
csv annotation file in the supplemental data or can be accessed in the \texttt{wells} variable
within R (as shown in \ref{S:ReFig}).

\subsection{Plate summaries}

\begingroup
\footnotesize
\begin{longtable}{ l l l l }
  Cell type & File names & Toxins (ng/ml) & Notes \\ \hline\hline
   \multirow{22}{*}{HCT8}  & 
              HCT8.txt & \specialcell{ A (500, 100, 10, 1, 0.1) \\
                                       B (500, 100, 10, 1, 0.1) } & \\ \cline{2-4}
   & \specialcell{HCT8-2a.txt\\ HCT8-2b.txt} & \specialcell{ B (1), A (100) \\
                                     gdTcdB (100, 1000) \\
                                     B (1) + gdTcdB (100) \\ B (1) + gdTcdB(1000) \\
                                     A (100) + gdTcdB (1000) } & toxins + gdTcdB \\ \cline{2-4}
   & HCT8-3.txt & \specialcell{ B (1), A (100) \\
                       gdTcdB (10, 100, 1000) \\
                       B (1) + gdTcdB (10) \\
                       B (1) + gdTcdB (100) \\
                       A (100) + gdTcdB (1000) } & toxins + gdTcdB \\ \cline{2-4}
   & HCT8-4.txt & \specialcell{ B (10, 100), A (100, 1000) \\
                       gdTcdB (100, 1000) \\
                       B (10) + gdTcdB (100) \\
                       B (10) + gdTcdB (1000) \\
                       B (100) + gdTcdB (100) \\
                       B (100) + gdTcdB (1000) \\
                       A (10) + gdTcdB (100) \\
                       A (100) + gdTcdB (100) \\
                       A (100) + gdTcdB (1000) \\
                       A (1000) + gdTcdB (1000) } & toxins + gdTcdB \\ \hline
   CHO & CHO.txt & \specialcell{ A (1000, 100, 1, 0.1, 0.01, 1e-3, 1e-4 ) \\
                                B (1000, 100, 1, 0.1, 0.01, 1e-3, 1e-4 ) } & \\ \hline
   IMCE & IMCE.txt & \specialcell{ A (1000, 100, 10, 1, 0.1, 0.01, 0.001 ) \\ 
                                         B (1000, 100, 10, 1, 0.1, 0.01, 0.001 )} &  \\ \hline
   HUVEC & \specialcell{HUVEC-a.txt\\ HUVEC-b.txt} &
           \specialcell{A (1000, 300, 100, 30, 10, 1, 0.1) \\
                        B (1000, 300, 100, 30, 10, 1, 0.1) } &  \\ \hline
   T84 & \specialcell{T84-a.txt \\ T84-b.txt } &
         \specialcell{A (300, 100, 30, 10, 3, 1, 0.1) \\
                      B (1000, 300, 100, 30, 10, 3, 1, 0.1) } &  \\ \hline
   \multirow{16}{*}{J774}  & \specialcell{ J774-a.txt \\ J774-b.txt} 
                          & \specialcell{ A (0.1, 1, 3, 10, 100, 300, 1000) \\
                                          B (0.1, 1, 3, 10, 100, 300, 1000) } & \\ \cline{2-4}
                          & J774-2.txt
                          & B (0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10) & \\ \cline{2-4}
                          & \specialcell{ J774-3a.txt \\ J774-3b.txt} 
                          & \specialcell{ A (10), B (0.01) \\
                                          gdTcdB (0.1, 1, 100) \\
                                          B (0.01) + gdTcdB (1) \\
                                          B (0.01) + gdTcdB (0.1) \\
                                          A (10) + gdTcdB (100) } & toxins + gdTcdB \\ \cline{2-4}
                          & J774-4.txt
                          & \specialcell{ A (3, 300), B (1, 100) \\
                                          gdTcdB (1, 100) \\
                                          A (10) + gdTcdB (100) } & toxins + gdTcdB \\ \cline{2-4}
                          & J774-5.txt
                          & \specialcell{ A (1, 1000), \\
                                          gdTcdB (10, 100) \\
                                          A (1) + gdTcdB (10) \\
                                          A (1000) + gdTcdB (1000) \\
                                          B (10) + gdTcdB (100) } & toxins + gdTcdB \\ \cline{2-4}
                          & J774-6.txt
                          & \specialcell{ A (0.1, 1, 10, 100, 1000), \\
                                          B (0.1, 1, 10, 100, 1000), \\
                                          gdTcdB (1, 10, 100), \\
                                          A (1) + gdTcdB (10) \\
                                          B (0.1) + gdTcdB (1) } & toxins + gdTcdB \\ \hline
   \multirow{8}{*}{PMN} & \specialcell{PMN-a.txt \\ PMN-b.txt} &
         \specialcell{A (10000, 7000, 5000, 3000, 1000, 500, 100) \\
                      B (10000, 7000, 5000, 3000, 1000, 500, 100) } & toxins + IL8 \\ \cline{2-4}
    & \specialcell{PMN-2a.txt \\ PMN-2b.txt} &
         \specialcell{A (1000, 100, 10, 1, 0.1, 0.01, 0.001) \\
                      B (1000, 100, 10, 1, 0.1, 0.01, 0.001) } & toxins alone \\ \cline{2-4}
    & PMN-3.txt &
         \specialcell{A (10, 100, 1000) \\
                      B (1, 10, 100, 1000) } & 
         \specialcell{ toxins alone and \\ toxins + IL8 } \\ \cline{2-4}
    & PMN-4.txt &
         \specialcell{A (10, 100, 1000) \\
                      B (10, 100, 1000) } & 
         \specialcell{ toxins alone and \\ toxins + IL8 } \\ \hline
   
\end{longtable}
\endgroup

\subsection{HCT8 cells}

First, a titration was performed to determine the number of HCT8 cells
needed to reach maximum impedance in a specified amount of time.

<<hct8_txt, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
subset = select(wells, file="HCT8.txt")
plot(subset, xlim=c(0,48), color="concentration", type="total", 
     replicates=TRUE, ID="cellSeed", sd=FALSE)
@

In the same experiment, the wells seeded with 5,000 cells were
used for a concentration-response experiment with TcdA and TcdB.

<<hct8_txt_b, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
A = normalize_toxin( select(subset, "HCT8[5000] & TcdA"))
B = normalize_toxin( select(subset, "HCT8[5000] & TcdB"))              
plotA = plot(A, color="concentration", ID="toxinAdd", xlim=c(-1,10)) + ggtitle("TcdA")
plotB = plot(B, color="concentration", ID="toxinAdd", xlim=c(-1,10)) + ggtitle("TcdB")
grid.arrange(plotA, plotB, nrow=1)  
@

In the next experiment, gdTcdB or TcdA+gdTcdB
and TcdB+gdTcdB combinations were added to HCT8 cells. gdTcdB had little effect within
the first ten hours, yet delayed the effects of TcdA and TcdB.

<<hct8-2_txt, tidy=TRUE, fig.width=7.5, fig.height=4.5>>=
subset = normalize_toxin(select(wells, file=c("HCT8-2a.txt","HCT8-2b.txt")), xlim=c(-1,10))
tox_plot = function(x, replicates=TRUE)
  plot(x, color="concentration", replicates=replicates) + ylim(c(0,1.2))
p1 = tox_plot( select(subset, "gdTcdB & !(TcdA | TcdB)")) + ggtitle("gdTcdB")
p2 = tox_plot( select(subset, "TcdA")) + ggtitle("TcdA")
p3 = tox_plot( select(subset, "TcdB")) + ggtitle("TcdB")
grid.arrange(p1, p2, p3, nrow=2)
@

The experiment was repeated again approximately one year later, yet
the variance of the growth of cells was high, presumably because of different
numbers of seeded cells in each well (note the last three panels
where the replicates are not averaged). This variance made it difficult to detect
any potential gdTcdB-induced delay of TcdA or TcdB's effects.

<<hct8-3_txt, tidy=TRUE, fig.width=7.5, fig.height=6.5>>=
subset0 = select(wells, "TcdA | TcdB | gdTcdB", file="HCT8-3.txt")
subset = normalize_toxin( subset0, xlim=c(-1,10) )
p1 = tox_plot(select(subset, "!TcdA & !TcdB")) + ggtitle("gdTcdB")
p2 = tox_plot(select(subset, "TcdA")) + ggtitle("TcdA")
p3 = tox_plot(select(subset, "TcdB")) + ggtitle("TcdB")
p4 = plot(subset0,color="concentration",xlim=c(0,50))
p5 = tox_plot(select(subset, "TcdA"), replicates=FALSE) + ggtitle("TcdA")
p6 = tox_plot(select(subset, "TcdB"), replicates=FALSE) + ggtitle("TcdA")
grid.arrange(p1, p2, p3, p4, p5, p6, nrow=3)
@   

Therefore, a similar experiment was again performed. The variance
among replicates was much tighter, and gdTcdB did indeed delay the
effects of TcdA and TcdB. However, at the higher concentration of TcdB (100 ng/ml),
this delay was not obvious; only one of the four samples showed a delay. The
reason for this outlier is unclear.

<<hct8-4_txt, tidy=TRUE, fig.width=7.5, fig.height=6.5>>=
subset = normalize_toxin( select(wells, file="HCT8-4.txt"), xlim=c(-1,12) )
p1 = tox_plot( select(subset, "gdTcdB & !(TcdA | TcdB)")) + ggtitle("gdTcdB")
p2 = tox_plot( select(subset, "TcdA[100]")) + ggtitle("TcdA 100 ng/ml")
p3 = tox_plot( select(subset, "TcdA[1000]")) + ggtitle("TcdA 1000 ng/ml")
p4 = tox_plot( select(subset, "TcdB[10]")) + ggtitle("TcdB 10 ng/ml")
p5 = tox_plot( select(subset, "TcdB[100]")) + ggtitle("TcdB 100 ng/ml")
p6 = tox_plot( select(subset, "TcdB[100]"), replicates=FALSE) + ggtitle("TcdB 100 ng/ml")
grid.arrange(p1, p2, p3, p4, p5, p6, nrow=3)
@

\subsection{CHO cells}

<<cho_txt, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
subset = normalize_toxin(select(wells, file="CHO.txt"))
p1 = plot(select(subset, "TcdA"), xlim=c(-1,20), color="concentration") + ggtitle("TcdA")
p2 = plot(select(subset, "TcdB"), xlim=c(-1,10), color="concentration") + ggtitle("TcdB")
grid.arrange(p1, p2, nrow=1)
@

\subsection{IMCE cells}

<<imce_txt, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
subset = normalize_toxin(select(wells, "IMCE"))
p1 = plot(select(subset, "TcdA"), color="concentration", xlim=c(-1,20), replicates=TRUE) + ggtitle("TcdA")
p2 = plot(select(subset, "TcdB"), color="concentration", xlim=c(-1,20), replicates=TRUE) + ggtitle("TcdB")
grid.arrange(p1, p2, nrow=1)
@

\subsection{HUVECs}

<<huvec_txt, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
subset = normalize_toxin(select(wells, "HUVEC"))
p1 = plot(select(subset, "TcdA"), color="concentration", xlim=c(-1,20), replicates=TRUE) + ggtitle("TcdA")
p2 = plot(select(subset, "TcdB"), color="concentration", xlim=c(-1,5), replicates=TRUE) + ggtitle("TcdB")
grid.arrange(p1, p2, nrow=1)
@

\subsection{T84 cells}

<<t84_txt, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
subset = normalize_toxin(select(wells, "T84"))
p1 = plot(select(subset, "TcdA"), color="concentration", xlim=c(-1,20)) + ggtitle("TcdA")
p2 = plot(select(subset, "TcdB"), color="concentration", xlim=c(-1,20)) + ggtitle("TcdB")
grid.arrange(p1, p2, nrow=1)
@

\subsection{J774 cells}

TcdA and TcdB were added to confluent J774 cells.

<<j774_txt, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
subset = normalize_toxin(select(wells, file=c("J774-a.txt","J774-b.txt")))
p1 = plot(select(subset,"TcdA"), xlim=c(-1,40), replicates=TRUE, color="concentration") + ggtitle("TcdA")
p2 = plot(select(subset,"TcdB"), xlim=c(-1,40), replicates=TRUE, color="concentration") + ggtitle("TcdB")
grid.arrange(p1, p2, nrow=1)
@

Since the lowest TcdB concentration tested in the first experiment
still had an effect, a fuller concentration-response experiment was
performed with TcdB. The lowest concentration to cause a response
was approximately 1 pg/ml.

<<j774-2_txt, tidy=TRUE, fig.width=3.3, fig.height=2.5, out.width="3.3in", out.height="2.5in">>=
subset = normalize_toxin(select(wells, file="J774-2.txt"))
plot(subset, replicates=TRUE, xlim=c(-1,24), color="concentration") + ggtitle("TcdB")
@

Like with HCT8 cells, gdTcdB was combined with TcdA and TcdB to
see if it delayed their effects. No delay was clearly observed, yet
gdTcdB alone elicited a distinct response at 100 ng/ml (but not 1 or 10 ng/ml).

<<j774-3_txt, tidy=TRUE, fig.width=7.5, fig.height=4.5>>=
subset = normalize_toxin(select(wells, file=c("J774-3a.txt","J774-3b.txt")))
tox_plot = function(x, replicates=TRUE) 
  plot(x, color="concentration", replicates=TRUE, xlim=c(-1,10))
p1 = tox_plot( select(subset, "gdTcdB & !(TcdA | TcdB)")) + ggtitle("gdTcdB")
p2 = tox_plot( select(subset, "TcdA")) + ggtitle("TcdA")
p3 = tox_plot( select(subset, "TcdB")) + ggtitle("TcdB")
grid.arrange(p1, p2, p3, nrow=2)
@

In the next experiment, toxin was added to subconfluent cells
for the sake of easier imaging of individual cells. The impedance
increases much more than with confluent cells likely because the spreading
of macrophages is more obvious when fewer cells are already covering
the electrodes before the toxin is added. Again, TcdB and gdTcdB at 100 ng/ml
induced a temporary increase in impedance followed by a long decrease.

<<j774-4_txt, tidy=TRUE, fig.width=7.5, fig.height=4.5>>=
subset = normalize_toxin(select(wells, file="J774-4.txt"))
tox_plot = function(x, replicates=TRUE, xlim=c(-1,24), ...) 
  plot(x, color="concentration", replicates=replicates, xlim=xlim, ...)
p1 = tox_plot( select(subset, "gdTcdB & !(TcdA | TcdB)")) + ggtitle("gdTcdB")
p2 = tox_plot( select(subset, "TcdA")) + ggtitle("TcdA")
p3 = tox_plot( select(subset, "TcdB")) + ggtitle("TcdB")
grid.arrange(p1, p2, p3, nrow=2)
@

Different combination of gdTcdB and TcdA or TcdB were added to cells
to explore other potential interactions. None were found; the effects
appeared to be additive.

<<j774-5_txt, tidy=TRUE, fig.width=7.5, fig.height=4.5>>=
subset = normalize_toxin(select(wells, file="J774-5.txt"))
p1 = tox_plot( select(subset, "gdTcdB & !(TcdA | TcdB)")) + ggtitle("gdTcdB")
p2 = tox_plot( select(subset, "TcdA")) + ggtitle("TcdA")
p3 = tox_plot( select(subset, "TcdB")) + ggtitle("TcdB")
grid.arrange(p1, p2, p3, nrow=2)
@

A sixth experiment was carried out with J774 cells to confirm the previous
findings. TcdB and gdTcdB at 100 ng/ml decreased J774 impedance; TcdA and
TcdB at lower concentrations increased impedance; and gdTcdB did not clearly
alter the affects of TcdA or TcdB.

<<j774-6_txt, tidy=TRUE, fig.width=7.5, fig.height=6.5>>=
subset = normalize_toxin(select(wells, file="J774-6.txt"))
p1 = tox_plot( select(subset, "gdTcdB & !(TcdA | TcdB)")) + ggtitle("gdTcdB")
p2 = tox_plot( select(subset, "TcdA[1]")) + ggtitle("TcdA 1 ng/ml")
p3 = tox_plot( select(subset, "TcdA & !TcdA[10] & !gdTcdB")) + ggtitle("TcdA")
p4 = tox_plot( select(subset, "TcdB[0.1] | gdTcdB[1-10] & !TcdA"), xlim=c(0,5)) + ggtitle("TcdB 0.1 ng/ml")
p5 = tox_plot( select(subset, "TcdB & !gdTcdB")) + ggtitle("TcdB")
grid.arrange(p1, p2, p3, p4, p5, nrow=3)
@

\subsection{PMN leukocytes}\label{S:PMNs}

Consistent response profiles of PMNs to TcdA or TcdB could not be obtained.
This is likely because unstimulated PMNs are not adherent and so
changes in shape are difficult to measure by impedance.

In the first experiment, only TcdA at 1,000 ng/ml was clearly different than control cells. Instead of
normalizing the impedance at the time toxin was added, the change in impedance
from the time of toxin addition is shown.

<<pmn-2_txt, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
subset = select(wells, file=c("PMN-2a.txt", "PMN-2b.txt"))
subset2 = transform(subset, c("tcenter","level"), ID="toxinAdd")
p1 = tox_plot( select(subset2, "TcdA")) + ggtitle("TcdA")
p2 = tox_plot( select(subset2, "TcdB")) + ggtitle("TcdB")
grid.arrange(p1, p2, nrow=1)
@

In the next experiment, cells were seeded in the presence 
of 100 ng/ml (9.01 nM) of human recombinant IL-8 in
an attempt to increase impedance before adding toxin.

<<pmn_txt, tidy=TRUE, fig.width=7.5, fig.height=2.5>>=
subset = select(wells, file=c("PMN-a.txt","PMN-b.txt"))
subset2 = transform(subset, c("tcenter","level"), ID="toxinAdd")
p1 = tox_plot( select(subset2, "!TcdB")) + ggtitle("TcdA")
p2 = tox_plot( select(subset2, "!TcdA"), xlim=c(-1,10)) + ggtitle("TcdB")
grid.arrange(p1, p2, nrow=1)
@

In another experiment, cells were seeded in the presence of 25 nM (277.45 ng/ml) of IL-8.
The results were not consistent with the previous experiment with IL-8.

<<pmn-3_txt, tidy=TRUE, fig.width=7.5, fig.height=4.5>>=
subset = select(wells, file="PMN-3.txt")
subset2 = transform(subset, c("tcenter","level"), ID="toxinAdd")
p1 = tox_plot( select(subset2, "(TcdA & IL8) | (IL8 & !TcdA & !TcdB)")) + ggtitle("TcdA+IL8")
p2 = tox_plot( select(subset2, "TcdA & !IL8")) + ggtitle("TcdA")
p3 = tox_plot( select(subset2, "(TcdB & IL8) | (IL8 & !TcdA & !TcdB)"), replicates=FALSE) + ggtitle("TcdB+IL8")
p4 = tox_plot( select(subset2, "TcdB & !IL8")) + ggtitle("TcdB")
grid.arrange(p1, p2, p3, p4, nrow=2)
@

Again, cells were seeded in the presence of 25 nM (277.45 ng/ml) of IL-8. The
machine temporarily stopped making impedance measurements from approximately
five to 20 hours.

<<pmn-4_txt, tidy=TRUE, fig.width=7.5, fig.height=4.5>>=
subset = select(wells, file="PMN-4.txt")
subset2 = transform(subset, c("tcenter","level"), ID="toxinAdd")
p1 = tox_plot( select(subset2, "(TcdA & IL8) | (IL8 & !TcdA & !TcdB)")) + ggtitle("TcdA+IL8")
p2 = tox_plot( select(subset2, "TcdA & !IL8")) + ggtitle("TcdA")
p3 = tox_plot( select(subset2, "(TcdB & IL8) | (IL8 & !TcdA & !TcdB)"), replicates=FALSE) + ggtitle("TcdB+IL8")
p4 = tox_plot( select(subset2, "TcdB & !IL8")) + ggtitle("TcdB")
grid.arrange(p1, p2, p3, p4, nrow=2)
@

\subsection{Plate Layouts}\label{S:plateLayouts}

Below are the layouts of all of the plates used.

<<plate-layouts, results="asis">>=
fwells = split(wells, filename(wells))
fwells = fwells[sort(names(fwells))]
latex.code = lapply( fwells, latex_layout, ID="toxinAdd", floating=FALSE, scalebox=0.6 )
do.call( cat, c("\\begin{adjustwidth}{0in}{3in}{",latex.code,"}\\end{adjustwidth}") )
@


%\printbibliography

\end{document}

