% formatting
\documentclass[10pt,a4paper,final]{article}
\usepackage{amssymb,latexsym}
\usepackage{graphicx}
\usepackage{authblk}
\usepackage[margin=0.75in]{geometry}
\usepackage{parskip}
\setlength{\parindent}{0pt}
\usepackage{textgreek}
\usepackage{pbox}
\usepackage{multirow}
\usepackage{changepage}
\usepackage{longtable}
\renewcommand{\thefigure}{M\arabic{figure}}

% command for making a table within the cell of a table
\newcommand{\specialcell}[2][c]{%
  \begin{tabular}[#1]{@{}l@{}}#2\end{tabular}}

% citations
\usepackage[url=false,
            backref=true,
            autocite=superscript,
            hyperref=true,
            style=nature,
            sorting=none,
            maxbibnames=99,
            minbibnames=99, 
            doi=false,url=false,isbn=false]{biblatex}
%\addbibresource{Manual.bib}
\AtEveryBibitem{\clearfield{issn}}
\AtEveryCitekey{\clearfield{issn}}
\DefineBibliographyStrings{english}{%
                                    backrefpage  = {see p.}, % for single page number
                                    backrefpages = {see pp.} % for multiple page numbers
}


% links
\usepackage{color}
\usepackage[usenames,dvipsnames,svgnames,table]{xcolor}
\usepackage[colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=blue]{hyperref}


\begin{document}
%\SweaveOpts{concordance=TRUE}

<<set-options, include=FALSE, cache=FALSE>>=
  opts_knit$set(root.dir="../../")
  opts_chunk$set(eval=TRUE,dev="png",dpi=400,tidy=FALSE,message=FALSE,cache=TRUE,warning=FALSE)
@

\title{Supplement}
\author[1]{\fontsize{10}{11}\selectfont Kevin~M. D'Auria}
             \author[2]{Meghan~J. Bloom}
             \author[2]{Yesenia Reyes}
             \author[2]{Mary~C. Gray}
             \author[2]{Edward~J. van Opstal}
             \author[1]{Jason~A. Papin}
             \author[2]{Erik~L. Hewlett}
             \affil[1]{Department of Biomedical Engineering} 
             \affil[2]{Division of Infectious Diseases and International Health\\
             Department of Medicine}
             \affil[ ]{University of Virginia, Charlottesville, VA}
             \date{}
             \maketitle

\hypersetup{linkcolor=black}
\setcounter{tocdepth}{2}
\tableofcontents
\hypersetup{linkcolor=blue}

<<libraries, tidy=TRUE, echo=TRUE>>=
library(wellz)
library(imTox)
wells = load_data()
@



\subsection{ Figure 1 }

<< preFigure2, tidy=FALSE, fig.width=7.5, fig.height=4.5, eval=TRUE, results='hide'>>=
figure_3(wells)
@

%\printbibliography

\end{document}



